# Generated by Django 3.0.2 on 2020-01-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='source_code',
            field=models.CharField(max_length=12),
        ),
    ]
