# Generated by Django 3.0.2 on 2020-01-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200123_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='live_demo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='source_code',
            field=models.URLField(),
        ),
    ]
