# Generated by Django 3.0.2 on 2020-01-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200123_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='tools',
        ),
    ]
